const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  ADD_ITEM_REQUEST: 'ADD_ITEM_REQUEST',  
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEM_REQUEST: 'REMOVE_ITEM_REQUEST',  
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_ITEM_FROM_CART_REQUEST: 'CLEAR_ITEM_FROM_CART_REQUEST'
};

export default CartActionTypes;
