const ProductDetailActionTypes = {
  FETCH_PRODUCT_DETAIL_START: 'FETCH_PRODUCT_DETAIL_START',
  FETCH_PRODUCT_DETAIL_SUCCESS: 'FETCH_PRODUCT_DETAIL_SUCCESS',
  FETCH_PRODUCT_DETAIL_FAILURE: 'FETCH_PRODUCT_DETAIL_FAILURE'
};
  
export default ProductDetailActionTypes;
  